### ISSUE TITLE
Intro 1 t /m 3

### ISSUE THREAD

**Issue by gglerum** [DOBronk/Hacklab-Huiswerk#1]
Ziet er netjes uit Dennis. Enige opmerkingen die ik heb zijn:

- Graag de comments in het Engels
- Vergeet de parameters van je functies niet te documenteren
- Vergeet de return types niet

Met return type bedoel ik:
```PHP
function handleInput(): bool|string
```
```PHP
function getRandomcard(): void
```

**Comment by DOBronk** [comment]
Resolved in:

https://github.com/DOBronk/Hacklab-Huiswerk/commit/685b3e667aa0c84c158d12cb2d6692fd52510f43
https://github.com/DOBronk/Hacklab-Huiswerk/commit/e739dd8c8ced3c2fe075923c9d15a79ede5a1cff
https://github.com/DOBronk/Hacklab-Huiswerk/commit/7074f5c35ec1a01e490120477ae9b619bf0bc632
