### ISSUE TITLE
Projecten/StudentManagement/src/Main.php

### ISSUE THREAD

**Issue by gglerum** [DOBronk/Hacklab-Huiswerk#2]
https://github.com/DOBronk/Hacklab-Huiswerk/blob/667c5247a053c24cce848da8682dfb099ca27ccd/Projecten/Student%20Management/src/Main.php#L33-L37

Kijk eens of je dit kunt oplossen met `array_filter`: https://www.php.net/manual/en/function.array-filter.php

https://github.com/DOBronk/Hacklab-Huiswerk/blob/667c5247a053c24cce848da8682dfb099ca27ccd/Projecten/Student%20Management/src/Main.php#L49C30-L49C50

Je hoeft hier geen dubbele haken te gebruiken.

**Comment by DOBronk** [comment]
Resolved in https://github.com/DOBronk/Hacklab-Huiswerk/commit/e0ed74926c1aa7715d2b1e4d808a0ddc14d49516
