### ISSUE TITLE
Projecten/Student Management/src /Index.php

### ISSUE THREAD

**Issue by gglerum** [DOBronk/Hacklab-Huiswerk#3]
Je kunt het iets overzichtelijker maken door de "sub" switches onder te brengen in functies. Dan wordt de switch in zijn geheel iets kleiner en overzichtelijker

**Comment by DOBronk** [comment]
Resolved in https://github.com/DOBronk/Hacklab-Huiswerk/commit/231313c83deaecfb4c7ed905d2a24d0fcf710e89
