### ISSUE TITLE
Projecten/Student%20Management/src/models/School.php

### ISSUE THREAD

**Issue by gglerum** [DOBronk/Hacklab-Huiswerk#4]
https://github.com/DOBronk/Hacklab-Huiswerk/blob/667c5247a053c24cce848da8682dfb099ca27ccd/Projecten/Student%20Management/src/models/School.php#L70

Als ik het niet verkeerd heb wordt hier een array aan `schoolClasses` toegevoegd, en niet een item met als key `$schoolclassId`. Is dat de bedoeling?

**Comment by DOBronk** [comment]
In principe had ik hier ook gewoon `$this->schoolClasses[$schoolclassId] = $schoolclass; ` moeten gebruiken, dat was veel beter geweest. Op de methode die ik heb gebruikt wordt er bij een associative array echter gemerged (beetje omslachtig voor slechts 1 key value pair), alleen met de + operator werkt het net even anders dan bij array_merge. De arrays mergen is hier in beide gevallen in ieder geval niet de meest elegante en efficientste optie.

Vind het zelf hier mooi uitgelegd het verschil: https://stackoverflow.com/questions/7059721/array-merge-versus

**Comment by DOBronk** [comment]
Alsnog aangepast in https://github.com/DOBronk/Hacklab-Huiswerk/commit/888126553ed18e95678b176e15fe656855d4dd45
