### ISSUE TITLE
Projecten/Student%20Management/src/models/SchoolClass.php

### ISSUE THREAD

**Issue by gglerum** [DOBronk/Hacklab-Huiswerk#5]
https://github.com/DOBronk/Hacklab-Huiswerk/blob/667c5247a053c24cce848da8682dfb099ca27ccd/Projecten/Student%20Management/src/models/SchoolClass.php#L31-L31

Je mag dit ook schrijven als: `$mentorid ?: false; `

**Comment by DOBronk** [comment]
Kende deze eerlijk gezegd nog niet, zo is het een stuk schonere code en kortere. Doorgevoerd in https://github.com/DOBronk/Hacklab-Huiswerk/commit/b2c4ec863e7fc08a12c26e2e19ecf21684ba9653
